services:
  client:
    image: rodneykim/team2_client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

  server:
    image: rodneykim/team2_server
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=db-tutor
      - DATABASE_URL=mongodb://mongodb:27017/db-tutor
    depends_on:
      - mongodb
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - app-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
